[package]
name = "rust-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
crossterm = "0.28.1"
ctrlc = "3.4.5"
nix = { version = "0.29.0", features = ["poll"] }
termios = "0.3.3"
